INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (1, 1, '2024', 'Jan', 'Azul', 63, 'Jabaquara');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (2, 1, '2024', 'Jan', 'Azul', 23, 'Conceição');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (3, 1, '2024', 'Jan', 'Azul', 13, 'São Judas');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (4, 1, '2024', 'Jan', 'Azul', 22, 'Saúde-Ultrafarma');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (5, 1, '2024', 'Jan', 'Azul', 13, 'Praça da Árvore');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (6, 1, '2024', 'Jan', 'Azul', 81, 'Santa Cruz');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (7, 1, '2024', 'Jan', 'Azul', 14, 'Vila Mariana');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (8, 1, '2024', 'Jan', 'Azul', 64, 'Ana Rosa');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (9, 1, '2024', 'Jan', 'Azul', 80, 'Paraíso');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (10, 1, '2024', 'Jan', 'Azul', 21, 'Vergueiro');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (11, 1, '2024', 'Jan', 'Azul', 17, 'São Joaquim');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (12, 1, '2024', 'Jan', 'Azul', 20, 'Japão-Liberdade');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (13, 1, '2024', 'Jan', 'Azul', 153, 'Sé');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (14, 1, '2024', 'Jan', 'Azul', 49, 'São Bento');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (15, 1, '2024', 'Jan', 'Azul', 116, 'Luz');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (16, 1, '2024', 'Jan', 'Azul', 11, 'Tiradentes');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (17, 1, '2024', 'Jan', 'Azul', 16, 'Armênia');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (18, 1, '2024', 'Jan', 'Azul', 43, 'Portuguesa-Tietê');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (19, 1, '2024', 'Jan', 'Azul', 9, 'Carandiru');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (20, 1, '2024', 'Jan', 'Azul', 41, 'Santana');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (21, 1, '2024', 'Jan', 'Azul', 9, 'Jardim São Paulo-Ayrton Senna');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (22, 1, '2024', 'Jan', 'Azul', 11, 'Parada Inglesa');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (23, 1, '2024', 'Jan', 'Azul', 47, 'Tucuruvi');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (24, 1, '2024', 'Jan', 'Verde', 62, 'Vila Prudente');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (25, 1, '2024', 'Jan', 'Verde', 62, 'Tamanduateí');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (26, 1, '2024', 'Jan', 'Verde', 33, 'Sacomã');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (27, 1, '2024', 'Jan', 'Verde', 14, 'Alto do Ipiranga');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (28, 1, '2024', 'Jan', 'Verde', 13, 'Santos-Imigrantes');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (29, 1, '2024', 'Jan', 'Verde', 70, 'Chácara Klabin');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (30, 1, '2024', 'Jan', 'Verde', 51, 'Ana Rosa');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (31, 1, '2024', 'Jan', 'Verde', 53, 'Paraíso');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (32, 1, '2024', 'Jan', 'Verde', 44, 'Brigadeiro');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (33, 1, '2024', 'Jan', 'Verde', 38, 'Trianon-Masp');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (34, 1, '2024', 'Jan', 'Verde', 81, 'Consolação');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (35, 1, '2024', 'Jan', 'Verde', 18, 'Clínicas');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (36, 1, '2024', 'Jan', 'Verde', 8, 'Santuário N.S. de Fátima-Sumaré');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (37, 1, '2024', 'Jan', 'Verde', 17, 'Vila Madalena');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (38, 1, '2024', 'Jan', 'Vermelha', 64, 'Corinthians-Itaquera');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (39, 1, '2024', 'Jan', 'Vermelha', 47, 'Artur Alvim');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (40, 1, '2024', 'Jan', 'Vermelha', 18, 'Patriarca-Vila Ré');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (41, 1, '2024', 'Jan', 'Vermelha', 18, 'Guilhermina-Esperança');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (42, 1, '2024', 'Jan', 'Vermelha', 22, 'Vila Matilde');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (43, 1, '2024', 'Jan', 'Vermelha', 23, 'Penha-Lojas Besni');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (44, 1, '2024', 'Jan', 'Vermelha', 35, 'Carrão-Assaí Atacadista');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (45, 1, '2024', 'Jan', 'Vermelha', 101, 'Tatuapé');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (46, 1, '2024', 'Jan', 'Vermelha', 32, 'Belém');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (47, 1, '2024', 'Jan', 'Vermelha', 25, 'Bresser-Moóca');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (48, 1, '2024', 'Jan', 'Vermelha', 48, 'Brás');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (49, 1, '2024', 'Jan', 'Vermelha', 14, 'Pedro II');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (50, 1, '2024', 'Jan', 'Vermelha', 172, 'Sé2');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (51, 1, '2024', 'Jan', 'Vermelha', 45, 'Anhangaba');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (52, 1, '2024', 'Jan', 'Vermelha', 107, 'República');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (53, 1, '2024', 'Jan', 'Vermelha', 19, 'Santa Cecília');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (54, 1, '2024', 'Jan', 'Vermelha', 22, 'Marechal Deodoro');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (55, 1, '2024', 'Jan', 'Vermelha', 126, 'Palmeiras-Barra Funda');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (56, 1, '2023', 'Jan', 'Azul', 63, 'Jabaquara');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (57, 1, '2023', 'Jan', 'Azul', 20, 'Conceição');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (58, 1, '2023', 'Jan', 'Azul', 12, 'São Judas');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (59, 1, '2023', 'Jan', 'Azul', 21, 'Saúde');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (60, 1, '2023', 'Jan', 'Azul', 12, 'Praça da Árvore');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (61, 1, '2023', 'Jan', 'Azul', 76, 'Santa Cruz');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (62, 1, '2023', 'Jan', 'Azul', 13, 'Vila Mariana');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (63, 1, '2023', 'Jan', 'Azul', 59, 'Ana Rosa');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (64, 1, '2023', 'Jan', 'Azul', 73, 'Paraíso');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (65, 1, '2023', 'Jan', 'Azul', 21, 'Vergueiro');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (66, 1, '2023', 'Jan', 'Azul', 17, 'São Joaquim');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (67, 1, '2023', 'Jan', 'Azul', 19, 'Japão-Liberdade');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (68, 1, '2023', 'Jan', 'Azul', 144, 'Sé');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (69, 1, '2023', 'Jan', 'Azul', 48, 'São Bento');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (70, 1, '2023', 'Jan', 'Azul', 108, 'Luz');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (71, 1, '2023', 'Jan', 'Azul', 10, 'Tiradentes');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (72, 1, '2023', 'Jan', 'Azul', 17, 'Armênia');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (73, 1, '2023', 'Jan', 'Azul', 43, 'Portuguesa-Tietê');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (74, 1, '2023', 'Jan', 'Azul', 8, 'Carandiru');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (75, 1, '2023', 'Jan', 'Azul', 41, 'Santana');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (76, 1, '2023', 'Jan', 'Azul', 8, 'Jardim São Paulo-Ayrton Senna');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (77, 1, '2023', 'Jan', 'Azul', 9, 'Parada Inglesa');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (78, 1, '2023', 'Jan', 'Azul', 47, 'Tucuruvi');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (79, 1, '2023', 'Jan', 'Vermelha', 64, 'Corinthians-Itaquera');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (80, 1, '2023', 'Jan', 'Vermelha', 46, 'Artur Alvim');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (81, 1, '2023', 'Jan', 'Vermelha', 17, 'Patriarca');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (82, 1, '2023', 'Jan', 'Vermelha', 17, 'Guilhermina-Esperança');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (83, 1, '2023', 'Jan', 'Vermelha', 21, 'Vila Matilde');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (84, 1, '2023', 'Jan', 'Vermelha', 22, 'Penha');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (85, 1, '2023', 'Jan', 'Vermelha', 34, 'Carrão');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (86, 1, '2023', 'Jan', 'Vermelha', 64, 'Tatuapé');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (87, 1, '2023', 'Jan', 'Vermelha', 31, 'Belém');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (88, 1, '2023', 'Jan', 'Vermelha', 24, 'Bresser-Mooca');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (89, 1, '2023', 'Jan', 'Vermelha', 66, 'Brás');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (90, 1, '2023', 'Jan', 'Vermelha', 14, 'Pedro II');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (91, 1, '2023', 'Jan', 'Vermelha', 164, 'Sé');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (92, 1, '2023', 'Jan', 'Vermelha', 42, 'Anhangabaú');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (93, 1, '2023', 'Jan', 'Vermelha', 101, 'República');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (94, 1, '2023', 'Jan', 'Vermelha', 19, 'Santa Cecília');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (95, 1, '2023', 'Jan', 'Vermelha', 22, 'Marechal Deodoro');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (96, 1, '2023', 'Jan', 'Vermelha', 119, 'Palmeiras-Barra Funda');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (97, 1, '2022', 'Jan', 'Azul', 53, 'Jabaquara');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (98, 1, '2022', 'Jan', 'Azul', 16, 'Conceição');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (99, 1, '2022', 'Jan', 'Azul', 10, 'São Judas');
INSERT INTO demandaPorEstacao (id, fk_empresa, ano, mes, linha, fluxo, estacao) VALUES (100, 1, '2022', 'Jan', 'Azul', 18, 'Saúde');